### ISSUE TITLE
Links to nodes that are not under Root are not recognized as pages.

### ISSUE THREAD

**Issue by Atzie** [Kentico/ems-mvc-components#128] opened 2020-06-03 07:19 UTC
### Brief bug description
This issue only happens when you select a page/node that is in a deeper level than directly under the root in the content tree. 

### Reproduction steps
1. Add a link in the rich text editor to a **child page** (meaning it has one or more parent pages)
![image](https://user-images.githubusercontent.com/5427497/83606467-0173f500-a5bd-11ea-9e0e-e4bb241a9b38.png)

2. Click on 'Save'
3. Edit the same link. The link is not being recognized as a page but as a general link. It also contains edit mode query string parameters.
![image](https://user-images.githubusercontent.com/5427497/83606548-25373b00-a5bd-11ea-8229-1fb6a0e2d7e8.png)
4. Save the page
5. Edit the same link again. The query string parameters have now been removed.
![image](https://user-images.githubusercontent.com/5427497/83607422-8dd2e780-a5be-11ea-8828-35fcedff0839.png)

### Expected behavior
1. Add a link in the rich text editor to a page that is located under the **Root**
![image](https://user-images.githubusercontent.com/5427497/83606260-a2ae7b80-a5bc-11ea-804a-262d34e19981.png)

2. Click on 'Insert'
3. Edit the same link
![image](https://user-images.githubusercontent.com/5427497/83606316-ba85ff80-a5bc-11ea-9744-53f5d52d9009.png)
4. Everything is working as expected.

### Test environment
- Version 1.2.1
 - Kentico MVC 12.0.43

### Additional context

Hoping this is not an edge case issue.

**Comment by petrinecp** [comment] 2020-06-03 10:19
Hi @Atzie, I've just tested this on Dancing Goat sample site and I was unable to reproduce your behavior. For further investigation, please submit a question on our [Support](https://devnet.kentico.com/support) Department and upload a backup of your project on our [FTP](https://devnet.kentico.com/support/ftp-instructions).

**Comment by Atzie** [comment] 2020-06-03 11:48
Hi @petrinecp, thanks for your time. I've further investigated the issue and it appears to be a bug when trying to compare the page URL with the URL pattern of a class/page type. The jist of it is that it compares the length of the alternative URL segments which does not match because we use a macro for the URL pattern. You should be able to reproduce this issue by having less segments (split string by slashes /) in your URL pattern than the node alias path. Hope this makes sense :) 
Is this something you can follow up on or should I create a ticket? Would like to get this resolved.

**Comment by petrinecp** [comment] 2020-06-03 14:20
Hi @Atzie, thank you for the clarification, this should be enough for me to reproduce this. I'll get back to you as soon as I'll have more info.

**Comment by OndraM-Kentico** [comment] 2020-08-03 13:39
This issue has been already fixed in version 12.0.76. Please, see my [comment here](https://github.com/Kentico/ems-mvc-components/issues/129#issuecomment-668026682).

**Closed** 2020-08-05 13:50 UTC
Labels: bug
