### ISSUE TITLE
Unable to Select from Page Tree when editing existing link elements in Rich Text Editor

### ISSUE THREAD

**Issue by johnventions** [Kentico/ems-mvc-components#105] opened 2020-02-07 20:20 UTC
### Brief bug description

The "Insert Link" Toolbar Button allows you to choose from the page tree upon initial creation of links. If the user attempts to change the link after creation, the "Select Page" button is no longer an option.

### Repro steps

1. Click the "Insert Link" button in the Rich Text Editor. (Or Ctrl + K)
2. Click on "General Link" and input any URL (i.e. "http://www.kentico.com")
3. Finish inserting link
4. Click the newly created link in Rich Text editor, and edit the link.
5. Note that there is no option to select from the page tree.

NOTE: Edited from originally submitted issue. Step 2 was originally:
 "Click on "Select Page" to choose a page from the page tree"

### Expected behavior

What the correct behavior is?

### Test environment

 - Chrome 79

**Comment by petrinecp** [comment] 2020-02-10 12:07
Hi @johnventions, when you edit a link there should be a change button under the selected page, like its visible on this gif here https://github.com/Kentico/ems-mvc-components/issues/100#issuecomment-580138240.

**Comment by OndraM-Kentico** [comment] 2020-02-18 16:55
@johnventions, any updates regarding your issue?

**Comment by johnventions** [comment] 2020-02-19 20:59
Hi @petrinecp & @OndraM-Kentico  - thank you (and sorry for the delay). I am going to update my original issue to clarify.

Steps:

1. Click the "Insert Link" button in the Rich Text Editor. (Or Ctrl + K)
2. Click on "General Link" and input any URL (i.e. "http://www.kentico.com")
3. Finish inserting link
4. Click the newly created link in Rich Text editor, and edit the link.
5. Note that there is no option to select from the page tree. User must remove link and start from Step 1.

**Comment by petrinecp** [comment] 2020-02-20 08:15
Hi @johnventions, I understand now, and yes if you want to change the type of the link you have to remove it first.

**Comment by OndraM-Kentico** [comment] 2020-02-21 16:55
@johnventions, we're going to close this as the behavior is "by design".

**Closed** 2020-02-24 06:39 UTC
Labels: invalid
