### ISSUE TITLE
Open in new tab doesn't work for page or media links

### ISSUE THREAD

**Issue by nwbowensby** [Kentico/ems-mvc-components#100] opened 2020-01-29 15:00 UTC
### Brief bug description

When you add a page link or a media link the "Open in new tab" setting doesn't work.  You can check it....but it doesn't output anything any different.

### Repro steps

1. Edit page and select some text in the rich text editor
2. Click the link toolbar button
3. Select either a page or media
4. Check the "Open in new tab" box
5. Click save
6. Check the link and note that target="_blank" is not set

### Test environment

Google Chrome 79.0.3945.130
Kentico 12SP - v12.0.55

**Comment by OndraM-Kentico** [comment] 2020-01-30 08:25
The issue you've described is not reproducible in our environment, see the gif below. If you have a look at the browser's console, is there any error? Based on the [screenshot](https://user-images.githubusercontent.com/50639553/73312246-80a78580-41e5-11ea-8e18-0f486b107e2a.png) you attached to #96 I noticed that "Open a new tab" field looks like if it was broken; is it a permanent state?

![rte-link-newtab](https://user-images.githubusercontent.com/15248835/73429725-9a0f1580-433c-11ea-8433-98fa3159c14b.gif)

**Comment by nwbowensby** [comment] 2020-01-30 14:11
I believe the difference is you are probably using a standard username.  Trying using a user name that has an @ sign in it like a email address.   I think then you'll see that the "Open in new Tab" doesn't stick.  I tried it using the administrator user on my end and it did work that way.

On the styling note I wondered about that but that is the only way I'd seen it until you showed me yours.  I'll see if there is a clash between our styling and yours.

**Comment by OndraM-Kentico** [comment] 2020-01-30 16:51
I don't think it's caused by "at" sign as I checked this scenario as well (can be seen in the gif above, when inspecting a link, its href contains user name with @ sign).

**Comment by nwbowensby** [comment] 2020-01-30 17:14
OndraM, the difference between your example and mine is I have an actual email address in the url...you just have an @ sign.  The regex for the email may be smart enough to not break things when an @ sign is included but since mine has bowensby@northernwater.org it takes it a step further.  There is already another confirmed bug that you guys are working on due to this.  I think this may just be another side affect.  The other bug is #96 which obviously isn't effecting you either as you aren't getting a mailto: in front of it.  I think what ever logic is thinking it is a mailto may also be ignoring the "Open in new tab".

**Comment by OndraM-Kentico** [comment] 2020-02-03 10:59
@nwbowensby I've managed to reproduce the issue on the tag v1.1.0-richtext. The reason I hadn't been able to before is that I was running on the latest master which contains merged #99. The PR also solves this issue. I'll let you know about the date of the next release.

**Comment by OndraM-Kentico** [comment] 2020-02-07 06:20
@nwbowensby I'm just letting you know that we plan to release a new package next week.

**Comment by nwbowensby** [comment] 2020-02-07 14:41
Thank you for letting me know.  Look forward to downloading it.

[cid:image002.png@01D5DD89.F3F9CC70]
Brandon Owensby | Application Developer II
220 Water Ave | Berthoud, CO 80513
Direct 970-622-2248

Main 800-369-RAIN (7246)
www.northernwater.org<http://www.northernwater.org> | Find us on Facebook<http://www.facebook.com/northernwater>

**Comment by OndraM-Kentico** [comment] 2020-02-18 17:03
Hi @nwbowensby, we've just released the v1.2.0, you can check whether it fixes your issue.

**Closed** 2020-02-24 06:39 UTC
