### ISSUE TITLE
Internal links result in the preview URL being exposed on the MVC site

### ISSUE THREAD

**Issue by Atzie** [Kentico/ems-mvc-components#129] opened 2020-06-03 07:42 UTC
### Brief bug description

Links to previews of pages started showing up on the website, exposing the preview functionality and personal information about the CMS user. The URLs came from the rich text editor and the problem is partially caused by issue #128 as that causes a link to a page to be turned into a general link. The problem with the **General Link** feature is that it causes absolute internal URLs to be transformed into the preview URL to the page. I suspect that issue #128 first occurred and then this issue right after it.

### Reproduction steps
1. Add a link in the rich text editor and select the General Link tab.
2. Add a URL that goes to a page on the site (absolute internal URL), make sure it contains the host.
![image](https://user-images.githubusercontent.com/5427497/83608075-9aa40b00-a5bf-11ea-92fb-fe3a5d8a6474.png)
3. Click 'Insert'
4. Save the page
5. Edit the same link
6. The result is that the URL has now changed to be the preview URL, which also exposes personal information about the user. At this stage is not stored like this however.
![image](https://user-images.githubusercontent.com/5427497/83608503-5b29ee80-a5c0-11ea-87b9-f198a5a7e6f5.png)
7. Save the page again. This will save the preview URL and will show it on the site.

### Expected behavior

The minimal expected behavior is that the given URL stays the same and not transformed into a preview URL. The desired behavior seems to be that the absolute internal URL is recognized as a page on the site and handle accordingly.

### Test environment

 - Version 1.2.1
 - Kentico 12.0.43

### Additional context

We have not noticed that this was an issue in earlier versions of the rich text editor. The issue also does not happen when using relative URLs.

**Comment by petrinecp** [comment] 2020-06-24 11:16
Hi @Atzie, we're currently working on fixing #128, once that issue is fixed we'll investigate this issue further or it's possible that it'll fix this issue as well.

**Comment by OndraM-Kentico** [comment] 2020-07-14 13:04
Hi @Atzie, we've found that #128 isn't the root cause of the issue.  Could you please tell me more about the scenario? How it happens that you use absolute page link and insert it as general link instead of just picking the page via the selector?

**Comment by Atzie** [comment] 2020-07-22 04:28
Hey @OndraM-Kentico , sure no problem. We use internal links as general links in the following scenarios:
- Linking to an alternative URL
- Link to an anchor on a page (e.g. `page/mypage#firstparagraph`)
- Using query string parameters (e.g `page/mypage?location=melbourne`)

There are currently no alternatives for these scenarios that I'm aware of. The anchors themselves are also added manually in the source on the pages using the rich text editor, as Froala does not seem to have an integrated way of adding them. Something to keep in mind while finding a solution is that the anchor and query string params should not be removed while processing the URL in the rich text editor.

Let me know if you need any more information 👍

**Comment by OndraM-Kentico** [comment] 2020-08-03 13:35
Hi @Atzie, I'm pleased to inform you that both your issues (#128 and #129) were fixed :) In both cases the fix happened in Kentico Libraries (not in this repository's code base). To apply the fix on your instance you need to upgrade Kentico NuGet packages to version 12.0.79 and apply the respective hotfix. Alternatively, you can wait for the Rich text package to be released---it will target the mentioned hotfix and packages and it will also deliver some new features like Rich text form component.

**Comment by OndraM-Kentico** [comment] 2020-08-05 13:50
FYI, rich text 1.3.0 has just been released 😉. I'm closing the issue for now; if you still experience the issue even after applying the hotfix, submit a new issue, please.

**Closed by OndraM-Kentico** 2020-08-05 13:50 UTC
Labels: bug
